import {
  BotInfo, BotStatus, GuildSummary, GuildDetails, PrefixConfig, AutomodConfig, TicketConfig,
  LevelingConfig, LoggingConfig, LeaderboardEntry, DiscordChannel, DiscordRole,
  AutoRoleConfig, AutoRoleUpdate, AdminStats, AdminConfig, AdminConfigUpdate,
  WelcomeConfig, AntiNukeConfig, VerificationConfig, VanityRoleSetup,
  TrackingConfig, J2CConfig, JoinDMConfig, CustomRoleConfig, AutoReactConfig,
  InvcConfig, RRConfig, ModulesConfig, ModuleState,
  InvitesLeaderboard,
} from "@/types/api";

export type ApiRequest = <T>(endpoint: string, options?: RequestInit) => Promise<T>;
type JsonObject = object;

export function createApi(request: ApiRequest) {
  return {
    getBotStatus: () => request<BotStatus>("/bot/status"),
    getBotInfo: () => request<BotInfo>("/bot/info"),
    listGuilds: () => request<GuildSummary[]>("/guilds/"),
    getGuildDetails: (guildId: string) => request<GuildDetails>(`/guilds/${guildId}`),
    getChannels: (guildId: string) => request<DiscordChannel[]>(`/guilds/${guildId}/channels`),
    getRoles: (guildId: string) => request<DiscordRole[]>(`/guilds/${guildId}/roles`),
    getPrefix: (guildId: string) => request<PrefixConfig>(`/guilds/${guildId}/prefix`),
    updatePrefix: (guildId: string, prefix: string) => request<{ status: string; new_prefix: string }>(`/guilds/${guildId}/prefix`, { method: "POST", body: JSON.stringify({ prefix }) }),
    getAutomod: (guildId: string) => request<AutomodConfig>(`/guilds/${guildId}/automod`),
    updateAutomod: (guildId: string, data: Partial<AutomodConfig>) => request<{ status: string }>(`/guilds/${guildId}/automod`, { method: "PATCH", body: JSON.stringify(data) }),
    getTickets: (guildId: string) => request<TicketConfig>(`/guilds/${guildId}/tickets`),
    updateTickets: (guildId: string, data: Record<string, unknown>) => request<{ status: string }>(`/guilds/${guildId}/tickets`, { method: "PATCH", body: JSON.stringify(data) }),
    getLeveling: (guildId: string) => request<LevelingConfig>(`/guilds/${guildId}/leveling`),
    updateLeveling: (guildId: string, data: Record<string, unknown>) => request<{ status: string }>(`/guilds/${guildId}/leveling`, { method: "PATCH", body: JSON.stringify(data) }),
    getLogging: (guildId: string) => request<LoggingConfig>(`/guilds/${guildId}/logging`),
    updateLogging: (guildId: string, data: Record<string, unknown>) => request<{ status: string }>(`/guilds/${guildId}/logging`, { method: "PATCH", body: JSON.stringify(data) }),
    getLeaderboard: (guildId: string) => request<LeaderboardEntry[]>(`/guilds/${guildId}/leveling/leaderboard`),
    getWelcome: (guildId: string) => request<WelcomeConfig>(`/guilds/${guildId}/welcome`),
    updateWelcome: (guildId: string, data: JsonObject) => request<{ status: string }>(`/guilds/${guildId}/welcome`, { method: "PATCH", body: JSON.stringify(data) }),
    getAntiNuke: (guildId: string) => request<AntiNukeConfig>(`/guilds/${guildId}/antinuke`),
    updateAntiNuke: (guildId: string, data: JsonObject) => request<{ status: string }>(`/guilds/${guildId}/antinuke`, { method: "PATCH", body: JSON.stringify(data) }),
    getVerification: (guildId: string) => request<VerificationConfig>(`/guilds/${guildId}/verification`),
    updateVerification: (guildId: string, data: JsonObject) => request<{ status: string }>(`/guilds/${guildId}/verification`, { method: "PATCH", body: JSON.stringify(data) }),
    getVanityRoles: (guildId: string) => request<VanityRoleSetup[]>(`/guilds/${guildId}/vanityroles`),
    addVanityRole: (guildId: string, data: Record<string, unknown>) => request<{ status: string }>(`/guilds/${guildId}/vanityroles`, { method: "POST", body: JSON.stringify(data) }),
    deleteVanityRole: (guildId: string, vanity: string) => request<{ status: string }>(`/guilds/${guildId}/vanityroles/${vanity}`, { method: "DELETE" }),
    getAutoRole: (guildId: string) => request<AutoRoleConfig>(`/guilds/${guildId}/autorole`),
    updateAutoRole: (guildId: string, data: AutoRoleUpdate) => request<{ status: string }>(`/guilds/${guildId}/autorole`, { method: "PATCH", body: JSON.stringify(data) }),
    getTracking: (guildId: string) => request<TrackingConfig>(`/guilds/${guildId}/tracking`),
    updateTracking: (guildId: string, data: Record<string, unknown>) => request<{ status: string }>(`/guilds/${guildId}/tracking`, { method: "PATCH", body: JSON.stringify(data) }),
    getJ2C: (guildId: string) => request<J2CConfig>(`/guilds/${guildId}/j2c`),
    updateJ2C: (guildId: string, data: Record<string, unknown>) => request<{ status: string }>(`/guilds/${guildId}/j2c`, { method: "PATCH", body: JSON.stringify(data) }),
    getJoinDM: (guildId: string) => request<JoinDMConfig>(`/guilds/${guildId}/joindm`),
    updateJoinDM: (guildId: string, data: Record<string, unknown>) => request<{ status: string }>(`/guilds/${guildId}/joindm`, { method: "PATCH", body: JSON.stringify(data) }),
    getCustomRoles: (guildId: string) => request<CustomRoleConfig>(`/guilds/${guildId}/customroles`),
    updateCustomRoles: (guildId: string, data: Record<string, unknown>) => request<{ status: string }>(`/guilds/${guildId}/customroles`, { method: "PATCH", body: JSON.stringify(data) }),
    getAutoReact: (guildId: string) => request<AutoReactConfig>(`/guilds/${guildId}/autoreact`),
    updateAutoReact: (guildId: string, data: Record<string, unknown>) => request<{ status: string }>(`/guilds/${guildId}/autoreact`, { method: "PATCH", body: JSON.stringify(data) }),
    getInvcRole: (guildId: string) => request<InvcConfig>(`/guilds/${guildId}/invcrole`),
    updateInvcRole: (guildId: string, data: Record<string, unknown>) => request<{ status: string }>(`/guilds/${guildId}/invcrole`, { method: "PATCH", body: JSON.stringify(data) }),
    getRR: (guildId: string) => request<RRConfig>(`/guilds/${guildId}/reactionroles`),
    updateRR: (guildId: string, data: Record<string, unknown>) => request<{ status: string }>(`/guilds/${guildId}/reactionroles`, { method: "PATCH", body: JSON.stringify(data) }),
    getInvites: (guildId: string) => request<InvitesLeaderboard>(`/guilds/${guildId}/invites`),
    getModules: (guildId: string) => request<ModulesConfig>(`/guilds/${guildId}/modules`),
    setModule: (guildId: string, moduleKey: string, enabled: boolean) => request<ModuleState>(`/guilds/${guildId}/modules/${moduleKey}`, { method: "PATCH", body: JSON.stringify({ enabled }) }),
    updateModules: (guildId: string, modules: Record<string, boolean>) => request<ModulesConfig>(`/guilds/${guildId}/modules`, { method: "PATCH", body: JSON.stringify({ modules }) }),
    getAdminStats: () => request<AdminStats>("/admin/stats"),
    getAdminConfig: () => request<AdminConfig>("/admin/config"),
    updateAdminConfig: (data: AdminConfigUpdate) => request<{ status: string }>("/admin/config", { method: "PATCH", body: JSON.stringify(data) }),
  };
}
