"""Registre central des modules activables/désactivables (Haunted).

Une seule source de vérité partagée par :
- l'API FastAPI (`api/routes/modules.py`),
- le garde côté bot (`core/zyrox.py` + `utils/modules.py`),
- le dashboard (`modules/page.tsx` + `modules-manager.tsx`).

Les `key` sont stables et utilisées comme clés en base (`db/modules.db`).
"""

MODULES = [
    {"key": "antinuke", "label": "Anti-Nuke", "description": "Protection contre les raids : bannissements, suppressions de salons/rôles et abus de webhooks.", "route": "antinuke"},
    {"key": "automod", "label": "Auto-modération", "description": "Anti-spam, anti-liens, anti-invitations, mentions de masse et spam d'emojis.", "route": "automod"},
    {"key": "tickets", "label": "Tickets", "description": "Assistance utilisateurs : panneau, catégories et rôles du staff.", "route": "tickets"},
    {"key": "verification", "label": "Vérification", "description": "Vérification des nouveaux membres avant l'accès au serveur.", "route": "verification"},
    {"key": "welcome", "label": "Bienvenue", "description": "Messages de bienvenue et départ, avec embeds personnalisables.", "route": "welcome"},
    {"key": "invites", "label": "Invitations", "description": "Suivi des invitations : total, faux comptes, départs et retours.", "route": "invites"},
    {"key": "autorole", "label": "Rôles automatiques", "description": "Rôles attribués automatiquement aux humains et aux bots.", "route": "autorole"},
    {"key": "reactionroles", "label": "Rôles à réactions", "description": "Obtenir des rôles en réagissant aux messages.", "route": "reactionroles"},
    {"key": "j2c", "label": "Salons temporaires", "description": "Salons vocaux temporaires (Join-to-Create) avec panneau de contrôle.", "route": "j2c"},
    {"key": "invcrole", "label": "Rôle vocal", "description": "Rôle attribué automatiquement en salon vocal.", "route": "invcrole"},
    {"key": "vanityroles", "label": "Rôles vanity", "description": "Rôles selon le statut personnalisé (vanity) des membres.", "route": "vanityroles"},
    {"key": "autoreact", "label": "Réactions auto", "description": "Réactions automatiques selon des déclencheurs.", "route": "autoreact"},
    {"key": "customroles", "label": "Rôles personnalisés", "description": "Rôles staff, VIP, invité… attribuables par commande.", "route": "customroles"},
    {"key": "joindm", "label": "MP de bienvenue", "description": "Message privé envoyé aux nouveaux membres.", "route": "joindm"},
    {"key": "leveling", "label": "Niveaux & XP", "description": "XP, niveaux et classement pour animer la communauté.", "route": "leveling"},
    {"key": "logging", "label": "Journaux", "description": "Journal détaillé des événements du serveur.", "route": "logging"},
    {"key": "games", "label": "Jeux & fun", "description": "Mini-jeux et commandes ludiques (blackjack, slots, counting…).", "route": None},
    {"key": "music", "label": "Musique", "description": "Lecture audio via Lavalink (file d'attente, boucle, recherche).", "route": None},
    {"key": "moderation", "label": "Modération", "description": "Bannir, expulser, muet, avertir, verrouiller…", "route": None},
]

MODULE_KEYS = [m["key"] for m in MODULES]
MODULE_LABELS = {m["key"]: m["label"] for m in MODULES}

# Correspondance nom de cog Discord -> clé de module (pour le garde `invoke()`).
COG_MODULE_MAP = {
    "Antinuke": "antinuke",
    "_antinuke": "antinuke",
    "AntiBan": "antinuke",
    "AntiBotAdd": "antinuke",
    "AntiChannelCreate": "antinuke",
    "AntiChannelDelete": "antinuke",
    "AntiChannelUpdate": "antinuke",
    "AntiEveryone": "antinuke",
    "AntiGuildUpdate": "antinuke",
    "AntiIntegration": "antinuke",
    "AntiKick": "antinuke",
    "AntiPrune": "antinuke",
    "AntiRoleCreate": "antinuke",
    "AntiRoleDelete": "antinuke",
    "AntiRoleUpdate": "antinuke",
    "AntiWebhookUpdate": "antinuke",
    "AntiWebhookCreate": "antinuke",
    "AntiWebhookDelete": "antinuke",
    "AntiMemberUpdate": "antinuke",
    "Automod": "automod",
    "_automod": "automod",
    "AntiSpam": "automod",
    "AntiCaps": "automod",
    "AntiLink": "automod",
    "AntiInvite": "automod",
    "AntiMassMention": "automod",
    "AntiEmojiSpam": "automod",
    "TicketCog": "tickets",
    "_ticket": "tickets",
    "Verification": "verification",
    "_verify": "verification",
    "Welcomer": "welcome",
    "_welcome": "welcome",
    "FastGreet": "welcome",
    "greet": "welcome",
    "inviteTracker": "invites",
    "Tracking": "invites",
    "AutoRole": "autorole",
    "Autorole": "autorole",
    "Autorole2": "autorole",
    "ReactionRoles": "reactionroles",
    "JoinToCreate": "j2c",
    "_J2C": "j2c",
    "Invcrole": "invcrole",
    "VanityRoles": "vanityroles",
    "_vanity": "vanity",
    "AutoReaction": "autoreact",
    "AutoReactListener": "autoreact",
    "Customrole": "customroles",
    "joindm": "joindm",
    "_joindm": "joindm",
    "Leveling": "leveling",
    "_leveling": "leveling",
    "Logging": "logging",
    "_logging": "logging",
    "Games": "games",
    "_games": "games",
    "Blackjack": "games",
    "Slots": "games",
    "Counting": "games",
    "_Counting": "games",
    "Fun": "games",
    "_fun": "games",
    "Music": "music",
    "_music": "music",
    "Moderation": "moderation",
    "_moderation": "moderation",
    "Ban": "moderation",
    "Unban": "moderation",
    "Mute": "moderation",
    "Unmute": "moderation",
    "Lock": "moderation",
    "Unlock": "moderation",
    "Hide": "moderation",
    "Unhide": "moderation",
    "Kick": "moderation",
    "Warn": "moderation",
    "Role": "moderation",
    "Message": "moderation",
}
